Feature
anas599/-Hello-Microverse-project pull request #1
Opened 2022-11-29 20:15 UTC by anas599

Opening pull request

2022-11-29 21:00 UTC, rskinnerc requested changes
Hi @anas599 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![giphy](https://user-images.githubusercontent.com/26911718/204640366-9789f0bc-3b87-4184-98e3-f467e21afaba.gif)

## Highlights
- Great work adding the required files to the `.gitignore` file 🤠
- Nice styling of your heading
- Good job setting GitHub actions 🙃

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 21:00 UTC, rskinnerc commented on .github/workflows/linters.yml
> +name: Linters
♻️ Hey there @anas599  your project is going great!!🤩 However, there are some things that you need to work on. Linters are super useful tools that allow you to find bugs even before compiling/shipping code. Right now, you have set the GitHub actions to run the linters. Good Job! Something missing is the configuration files for the linters.

- [ ] Please double-check the [linters config guide](https://github.com/microverseinc/linters-config/tree/master/html-css) and kindly add the missing files⚙️. they are need while running the GitHub Actions

2022-11-29 21:00 UTC, rskinnerc commented on README.md
> +  <h3><b>Hello Microverse README file</b></h3>
♻️ Nice job! You are using the recommended template provided by Microverse. However, you might need to fix some things to make it look even more professional.

- [ ] The logo was removed, it seems like it is a broken link. Please, either remove the logo from the template or add a custom logo. 🖼️

Please keep reading my comments

2022-11-29 21:00 UTC, rskinnerc commented on README.md
> +- [📖 About the Project](Hello Microverse)
♻️ The table of contents is just a list of links to other sections of the README. 

- [ ] Please do not put any custom information there. Kindly use the intended sections:

![image](https://user-images.githubusercontent.com/26911718/204642044-56b949c2-0802-4963-8467-770945c39703.png)

2022-11-29 21:00 UTC, rskinnerc commented on README.md
> +  - [Deployment](#triangular_flag_on_post-deployment)
[OPTIONAL] In future projects, you probably will need all the sections. However, you can remove the subsections when not applicable.

2022-11-29 21:00 UTC, rskinnerc commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
♻️ This is one of the most important parts of the README file. Recruiters and hiring managers would be glad to find your contact information here.

- [ ] Please add your name and accounts here as suggested 📱. This will make look your work way more professional.

2022-11-29 21:00 UTC, rskinnerc commented on README.md
> +This project is [MIT](./LICENSE) licensed.
♻️ Adding a license is a great idea. However, always make sure the link provided is working. Currently, the link to the `./LICENSE` is broken (404 not found)

- [ ] Please add a valid license and fix the link to it. [This repo](https://github.com/microverseinc/readme-template) also contains a valid MIT license and how to use it.

2022-11-29 21:00 UTC, rskinnerc commented on index.html
> +    <title>Document</title>
[OPTIONAL] It is always a good idea to give a more meaningful or descriptive title to your page. Making it a habit will make you a better dev!  🤓🤓

2022-11-29 21:00 UTC, rskinnerc commented on index.html
> +<!DOCTYPE html>
♻️ Great Job with the `index.html` file 😉😉!! However, there are some other points in your project that you need to work on (please note I'm just adding them here in the index so you can track them better):

- [ ] Please give a more meaningful PR title. It should summarize the changes your made (i.e. Set-up linters and added initial project files)
- [ ] Kindly, update the PR summary. It should describe the introduced changes in more detail. It is part of the good documentation of your work. 🤖🤖

[OPTIONAL] Good job with the commit messages, they describe what you did. However, please remember for **future projects (it is required!)** that _the commit message should be written in the imperative tense and capitalized._ That is, instead of writing 

> Added .gitignore file to feature branch

it should be

> Add .gitignore file to feature branch

[OPTIONAL] You are currently using GitHub Flow as required 🦾🦾. However, for **future projects** the name of the feature branch should be more descriptive, for example, instead of using `feature` as the name, you could say something like `project-setup` or `add-mobile-menu`. Remember in a collaborative environment, this helps document the work you have done from the very beginning.

2022-11-29 21:54 UTC, Alfredbis29 approved these changes
# STATUS: APPROVED  
 ## Hi @anas599 ,
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Your repo is professional :white_check_mark:
 * Well structured files :white_check_mark:
 * No Linter errors :white_check_mark:
 
 Now you can merge this branch and move on :1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers four_leaf_clover:

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
 
 ## Optional suggestions
- [ ] Kindly make sure to document your README professionally. Please use the [Microverse README template](https://github.com/microverseinc/readme-template) and customize it. as required by the previous review
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 21:54 UTC, Alfredbis29 commented on README.md
> +# 📗 Table of Contents
- [ OPTIONAL] You should consider using microverse's logo in your  :wink:

2022-11-29 21:54 UTC, Alfredbis29 commented on README.md
> +
- [ OPTIONAL]  I Can see that you have two authors here but this is a solo project you should remove one author here :wink:

2022-11-29 22:00 UTC, merged

2022-11-30 09:20 UTC, OyePriscilla reviewed
## Hi @anas599 😃  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Descriptive pull request message and title :heavy_check_mark: 
Linter error checks validated :heavy_check_mark: 
Commit messages are meaningful. :heavy_check_mark: 
GitHub flow observed ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 09:27 UTC, anas599 commented
Hi OyePriscilla, It shows in my progress that I have to submit the project and it is not completed?
Or should I wait?
and also it is already merged,
Thanks.

> ## Hi @anas599 😃 ,
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> ![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif) [ ![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif) ](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif) [ ](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)
> 
> ## Highlights
> Descriptive pull request message and title ✔️ Linter error checks validated ✔️ Commit messages are meaningful. ✔️ GitHub flow observed ✔️
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 12:06 UTC, OyePriscilla commented
@anas599 You can go ahead and submit it, in as much your project is approved. Thanks.